/** @type {import('tailwindcss').Config} */

module.exports = {
  future: {
    hoverOnlyWhenSupported: true,
  },
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      container: {
        center: true,
        padding: "1.5rem",
        screens: {
          "2xl": "1360px",
        },
      },
      fontFamily: {
        satoshi: ["Satoshi", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        sans: [
          "Lato",
          "Lucida Grande",
          "Lucida Sans Unicode",
          "Tahoma",
          "Sans-Serif",
        ],
        header: ["Telefon Black", "Sans-Serif"],
        "header-alt": ["Telefon", "Sans-Serif"],
        monospace: [
          "SFMono-Regular",
          "Consolas",
          "Liberation Mono",
          "Menlo",
          "monospace",
        ],
      },
      colors: {
        "primary-orange": "#FF5722",
        "cp-color-1": "var(--cp-color-1)",
        "cp-color-2": "var(--cp-color-2)",
        "cp-color-3": "#131417",
        "cp-color-4": "#010101",
        "cp-color-5": "#9B9DAD",
        "cp-color-6": "#252830",
        "cp-color-7": "#717790",
        "cp-color-8": "#444857",
        "cp-color-9": "#5A5F73",
        "cp-color-10": "#248C46",
        "cp-color-11": "#47CF73",
        "cp-color-12": "#1E1F26",
        "cp-color-13": "var(--cp-color-13)",
        "cp-color-14": "var(--cp-color-14)",
        "cp-color-15": "var(--cp-color-15)",
        "cp-color-16": "var(--cp-color-16)",
        "cp-color-17": "var(--cp-color-17)",
        "cp-color-18": "var(--cp-color-18)",
        "cp-color-19": "var(--cp-color-19)",
        "cp-color-20": "var(--cp-color-20)",
        "cp-color-shadow": "var(--cp-color-shadow)",
        "cp-color-green": "var(--cp-color-green)",
        "cp-color-green-light": "var(--cp-color-green-light)",
        "cp-color-green-dark": "var(--cp-color-green-dark)",
        "cp-color-yellow": "var(--cp-color-yellow)",
        "cp-color-yellow-light": "var(--cp-color-yellow-light)",
        "cp-color-yellow-dark": "var(--cp-color-yellow-dark)",
        "cp-color-purple": "var(--cp-color-purple)",
        "cp-color-purple-light": "var(--cp-color-purple-light)",
        "cp-color-purple-dark": "var(--cp-color-purple-dark)",
        "cp-color-red": "var(--cp-color-red)",
        "cp-color-red-very-light": "var(--cp-color-red-very-light)",
        "cp-color-red-light": "var(--cp-color-red-light)",
        "cp-color-red-dark": "var(--cp-color-red-dark)",
        "cp-color-blue": "var(--cp-color-blue)",
        "cp-color-blue-light": "var(--cp-color-blue-light)",
        "cp-color-blue-dark": "var(--cp-color-blue-dark)",
        "cp-color-link": "var(--cp-color-link)",
        "cp-color-link-on-white": "var(--cp-color-link-on-white)",
        "cp-color-link-on-black": "var(--cp-color-link-on-black)",
        "cp-color-pens": "var(--cp-color-pens)",
        "cp-color-posts": "var(--cp-color-posts)",
        "cp-color-collections": "var(--cp-color-collections)",
        "cp-color-projects": "var(--cp-color-projects)",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
