import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Header from "../components/Header";
import About from "../components/About";
import Workouts from "../components/Workouts";
import Pricing from "../components/Pricing";
import Community from "../components/Community";
import Faq from "../components/Faq";
import Join from "../components/Join";
import Footer from "../components/Footer";

import Aos from "aos";
import "aos/dist/aos.css";

export default function Home() {
  useEffect(() => {
    Aos.init({
      duration: 2500,
      delay: 400,
    });
  }, []);

  return (
    <div className="max-w-[1440px] mx-auto bg-page overflow-hidden relative">
      <Head>
        <title>GymGym</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Header */}
      <Header />
      {/* Banner */}
      <Banner />
      {/* About */}
      <About />
      {/* Workouts */}
      <Workouts />
      {/* Pricing */}
      <Pricing />

      {/* Community */}
      <Community />

      {/* FAQ */}
      <Faq />

      {/* Join */}
      <Join />

      {/* Footer */}
      <Footer />

    </div>
  );
}
